server:
  port: 8003

spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.101:8848

aliyun:
  vod:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tQXwarrffJxLiSPNyiy
      keysecret: eFl4vkyYnoKC8J2YsNHJyexis8LFCX
      bucketname: guo-edu




